# Generated by Django 6.1 on 2026-09-04 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='MFS sender number (bKash/Nagad/Rocket) or last 4 digits of card, when applicable.', max_length=50, null=True),
        ),
    ]
